# Generated by Django 3.2.7 on 2021-09-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
